DROP DATABASE IF EXISTS DW3_TALAMO_EMILIANO;
CREATE DATABASE DW3_TALAMO_EMILIANO
	DEFAULT CHARACTER SET utf8 DEFAULT
	COLLATE utf8_general_ci;
USE DW3_TALAMO_EMILIANO;

CREATE TABLE users(
	ID INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	MAIL VARCHAR(100) NOT NULL UNIQUE,
	HANDLE VARCHAR(15) NOT NULL UNIQUE,
	NAME VARCHAR(20),
	BIO VARCHAR(160),
	PASSWORD CHAR(40),
	STATUS ENUM('INACTIVE', 'NEW', 'ACTIVE', 'ADMIN'),
	REGISTER_DATE DATE
)ENGINE=innoDB;

CREATE TABLE cientocuarentas(
	ID INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	FKUSER_ID INT UNSIGNED,
	CONTENT VARCHAR(140) NOT NULL,
	DATE DATETIME,

	FOREIGN KEY(FKUSER_ID) REFERENCES users(ID) ON DELETE CASCADE ON UPDATE CASCADE
)ENGINE=innoDB;

CREATE TABLE favs(
	FKUSER_ID INT UNSIGNED,
	FKCIENTOCUARENTA_ID INT UNSIGNED,
	PRIMARY KEY(FKUSER_ID, FKCIENTOCUARENTA_ID),

	FOREIGN KEY(FKUSER_ID) REFERENCES users(ID) ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY(FKCIENTOCUARENTA_ID) REFERENCES cientocuarentas(ID) ON DELETE CASCADE ON UPDATE CASCADE
)ENGINE=innoDB;

CREATE TABLE follows(
	THISUSER_ID INT UNSIGNED,
	FOLLOWSTHISUSER_ID INT UNSIGNED,

	FOREIGN KEY(THISUSER_ID) REFERENCES users(ID) ON DELETE CASCADE ON UPDATE CASCADE
)ENGINE=innoDB;

CREATE TABLE banner(
	ID INT UNSIGNED PRIMARY KEY,
	LINK VARCHAR(256),
	PIC LONGBLOB
)ENGINE=innoDB;

ALTER TABLE users AUTO_INCREMENT = 1;
